### ISSUE TITLE
feat(data modelling): Implementation of Product Weight Component with Associated Fields

### ISSUE THREAD

**Issue by RitaDee** [distributeaid/aggregated-public-information#14]
I propose the creation of a product weight component along with associated fields based on product specifications within the table. The envisioned fields include:

- Package weight (numeric)
- Weight unit (select)
- Count per package (numeric)
- Item weight (numeric)
- Count per kg (numeric)
- Weight source (text)
- Log date (date)
- Notes (text)

Issue Goals:

- [ ] Develop the product.weight component.
- [ ] Integrate the product.weight component with the product item collection.
- [ ] Enable the linkage of multiple product.weight instances to a product item.

**Comment by jtfairbank** [comment]
@RitaDee looking good!  A few suggestions using [conventional comments](https://conventionalcomments.org/):

- suggestion(blocking): make the `weight unit` some sort of select field with preset options.  fine to update the issue after you start working on a branch and can explore what fields Strapi has to offer.  you can see the options we have in the spreadsheet
- suggestion: since you can't have a `/` in the field name, i'd suggest replacing it with "per".  so "count / package" => "count per package" and "count / kg" => "count per kg"
- note: `item weight` and `count / kg` are calculated fields.  we can make them manually enter-able for now to get the model right, but down the road we'll want to hide them from the Strapi content entry form and instead calculate them when we create / update an item.
    - to calculate `item weight`: normalize the `package weight` to kilograms, then divide by the `count/package`
    - to calculate `count / kg`: inverse the `item weight` (ie `1 / item_weight`)

Feel free to get started coding!  You can always adjust your issue as you go!

**Comment by RitaDee** [comment]
> @RitaDee looking good! A few suggestions using [conventional comments](https://conventionalcomments.org/):
> 
> * suggestion(blocking): make the `weight unit` some sort of select field with preset options.  fine to update the issue after you start working on a branch and can explore what fields Strapi has to offer.  you can see the options we have in the spreadsheet
> * suggestion: since you can't have a `/` in the field name, i'd suggest replacing it with "per".  so "count / package" => "count per package" and "count / kg" => "count per kg"
> * note: `item weight` and `count / kg` are calculated fields.  we can make them manually enter-able for now to get the model right, but down the road we'll want to hide them from the Strapi content entry form and instead calculate them when we create / update an item.
>   
>   * to calculate `item weight`: normalize the `package weight` to kilograms, then divide by the `count/package`
>   * to calculate `count / kg`: inverse the `item weight` (ie `1 / item_weight`)
> 
> Feel free to get started coding! You can always adjust your issue as you go!

Thank you, @jtfairbank, for the review I have made the changes. I will start working on this issue ASAP.
